version: '3.8'

services:
  node:
    image: node:18
    volumes:
      - .:/app
      - /app/bootstrap/node_modules
      - /app/bootstrap/.next
      - /app/react-bootstrap/node_modules
      - /app/react-bootstrap/.next
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true
